// Command gendocs renders docs/reference/commands.md from the adapter's
// command tables so the reference never drifts from the code.
//
//	go run ./tools/gendocs            # write docs/reference/commands.md
//	go run ./tools/gendocs -o -       # print to stdout
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/jneo8/mcp-juju/pkg/jujuadapter"
)

const defaultOutput = "docs/reference/commands.md"

func main() {
	output := flag.String("o", defaultOutput, "output file, or - for stdout")
	flag.Parse()

	doc, err := Render()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if *output == "-" {
		fmt.Print(doc)
		return
	}
	if err := os.WriteFile(*output, []byte(doc), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// Render produces the Markdown for the command reference.
func Render() (string, error) {
	commands, err := jujuadapter.DescribeCommands()
	if err != nil {
		return "", err
	}

	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	yn := func(v bool) string {
		if v {
			return "yes"
		}
		return "no"
	}

	w("# Command reference")
	w("")
	w("<!-- Generated by `just docs-commands` (tools/gendocs). Do not edit by hand. -->")
	w("")
	w("Every MCP tool corresponds to one Juju 3.6 CLI command and carries the same name. This page lists all %d tools with their [MCP tool annotations](https://modelcontextprotocol.io/specification/2026-07-28/server/tools#tool-annotations) and their availability in [read-only mode](read-only-mode.md). Tools are listed in the order the Juju CLI registers them, which is also the order returned by `tools/list`.", len(commands))
	w("")
	w("Column meanings:")
	w("")
	w("| Column | Meaning |")
	w("|---|---|")
	w("| Read-only | `readOnlyHint`: the tool does not modify Juju state or the host |")
	w("| Destructive | `destructiveHint`: the tool removes or replaces state, or upgrades software |")
	w("| Idempotent | `idempotentHint`: repeating the call with the same arguments has no additional effect |")
	w("| Open world | `openWorldHint`: the tool contacts a service other than the Juju controller (Charmhub, an arbitrary host, a URL) |")
	w("| In read-only mode | `yes`: registered as is; `no`: not registered; `policy`: registered, calls accepted only in the described shape |")
	w("")
	w("## Tools")
	w("")
	w("| Tool | Purpose | Read-only | Destructive | Idempotent | Open world | In read-only mode |")
	w("|---|---|---|---|---|---|---|")
	for _, c := range commands {
		w("| `%s` | %s | %s | %s | %s | %s | %s |", c.Name, c.Purpose, yn(c.ReadOnly), yn(c.Destructive), yn(c.Idempotent), yn(c.OpenWorld), c.ReadOnlyMode)
	}
	w("")
	w("## Commands not exposed")
	w("")
	w("These Juju 3.6 CLI commands are not available as tools because their constructors are unexported in `github.com/juju/juju/cmd/juju/commands`:")
	w("")
	w("| Command | Purpose |")
	w("|---|---|")
	for _, c := range jujuadapter.UnexposedCommands {
		w("| `%s` | %s |", c.Name, c.Purpose)
	}
	w("")
	w("Aliases of the Juju CLI (for example `list-models` for `models`, `relate` for `integrate`, `add-relation` for `integrate`) are not registered; only the canonical name is a tool.")
	return b.String(), nil
}
